name: EggAlarm
main: de.mahagst.risingworld.eggalarm.EggAlarmPlugin
version: 1.0.1
api: 0.9.3.2
author: mahagst
description: Alarm clock for cooking and stuff.
website: https://api.github.com/repos/HaggerShose/rw-egg-alarm/releases/latest
